This is about exceptions in python
